server:
  port: 5000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://awseb-e-grqw2ijm82-stack-awsebrdsdatabase-cqrqezwadurf.ccauxoeq2jfo.ap-northeast-2.rds.amazonaws.com:3306
    username: holdMyHand
    password: rejin0421
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    show-sql: true